ServerGroveKbBundle_Admin_Articles_Files:
    resource: "@ServerGroveKbBundle/Controller/Admin/ArticlesFilesController.php"
    type:     annotation

ServerGroveKbBundle_Admin_Articles:
    resource: "@ServerGroveKbBundle/Controller/Admin/ArticlesController.php"
    type:     annotation

ServerGroveKbBundle_Admin_Categories:
    resource: "@ServerGroveKbBundle/Controller/Admin/CategoriesController.php"
    type:     annotation

ServerGroveKbBundle_Admin_Default:
    resource: "@ServerGroveKbBundle/Controller/Admin/DefaultController.php"
    type:     annotation

ServerGroveKbBundle_Admin_Urls:
    resource: "@ServerGroveKbBundle/Controller/Admin/UrlsController.php"
    type:     annotation

ServerGroveKbBundle_Admin_Users:
    resource: "@ServerGroveKbBundle/Controller/Admin/UsersController.php"
    type:     annotation

ServerGroveKbBundle_Articles:
    resource: "@ServerGroveKbBundle/Controller/ArticlesController.php"
    type:     annotation

ServerGroveKbBundle_Categories:
    resource: "@ServerGroveKbBundle/Controller/CategoriesController.php"
    type:     annotation

ServerGroveKbBundle_Default:
    resource: "@ServerGroveKbBundle/Controller/DefaultController.php"
    type:     annotation
